steps:
  - name: 'us-east1-docker.pkg.dev/gcp-asigbahgcp-nprd-47930/bah-builders/bah-kali-linux-img'
    env:
      - 'KALI_VERSION=2024.2'
      - 'CML_ENDPOINT=https://gcp.becomingahacker.com'
      - 'GS_IMAGE_PATH=gs://bah-machine-images/kali-linux'
      # Pristine
      #- 'SOURCE_IMAGE_FAMILY=kali-linux-cloud-gce-amd64'
      # Tweaks
      - 'SOURCE_IMAGE_FAMILY=kali-linux-cloud-cml-amd64'
      # Pristine
      #- 'PROVISION_SCRIPT=setup.sh'
      # Tweaks
      - 'PROVISION_SCRIPT=tweaks.sh'
      - 'APT_OPTS="-o Dpkg::Options::=--force-confmiss -o Dpkg::Options::=--force-confnew -o DPkg::Progress-Fancy=0 -o APT::Color=0"'
      - 'DEBIAN_FRONTEND=noninteractive'
      - 'TZ=Etc/UTC'
      - 'PACKER_LOG=1'
      - 'LOCATION=$LOCATION'
      - 'PROJECT_ID=$PROJECT_ID'
      - 'ZONE=$LOCATION-b'
      - 'SERVICE_ACCOUNT_EMAIL=$SERVICE_ACCOUNT_EMAIL'

    script: |
      #!/usr/bin/env bash

      set -e
      #set -x

      env

      echo "Locale settings:"
      cat /etc/default/locale

      # SSH key pair for Packer.  Will be removed after build.
      mkdir -vp secrets
      ssh-keygen -t ed25519 -f secrets/id_ed25519 -C "root@kali" -N ""

      # Build Kali Linux image with Packer
      packer init kali-gce.pkr.hcl
      packer validate \
        -var "service_account_email=$SERVICE_ACCOUNT_EMAIL" \
        -var "zone=$ZONE" \
        -var "project_id=$PROJECT_ID" \
        -var "source_image_family=$SOURCE_IMAGE_FAMILY" \
        -var "provision_script=$PROVISION_SCRIPT" \
        kali-gce.pkr.hcl
      packer build \
        -var "service_account_email=$SERVICE_ACCOUNT_EMAIL" \
        -var "zone=$ZONE" \
        -var "project_id=$PROJECT_ID" \
        -var "source_image_family=$SOURCE_IMAGE_FAMILY" \
        -var "provision_script=$PROVISION_SCRIPT" \
        kali-gce.pkr.hcl

      jq . manifest.json

      IMAGE=$(jq -r .builds[0].artifact_id manifest.json)

      gcloud compute images export \
        --compute-service-account $SERVICE_ACCOUNT_EMAIL \
        --cloudbuild-service-account $SERVICE_ACCOUNT_EMAIL \
        --zone $ZONE \
        --image $IMAGE \
        --log-location ${GS_IMAGE_PATH} \
        --export-format qcow2 \
        --destination-uri ${GS_IMAGE_PATH}/${IMAGE}.qcow2

logsBucket: 'gs://bah-build-logs/bah-kali-linux-img'
serviceAccount: 'projects/gcp-asigbahgcp-nprd-47930/serviceAccounts/build-bah-kali-linux-img@gcp-asigbahgcp-nprd-47930.iam.gserviceaccount.com'

options:
  logging: GCS_ONLY
  logStreamingOption: STREAM_ON
