steps:
  - name: 'ubuntu'
    args: ['echo', 'hello world'] 
  
  - name: 'ubuntu'
    args:
      - ls
      - -l
      - /workspace
  - name: 'ubuntu'
    script: |
      #!/usr/bin/env bash
      echo "Hello $_USER"
  - name: 'ubuntu'
    script: |
      #!/usr/bin/env bash
      echo "Your project ID is $PROJECT_ID"

#  - name: 'us-east1-docker.pkg.dev/gcp-asigbahgcp-nprd-47930/cmm/cloud-sdk@sha256:edbae5f175701d837754cbf5402b4c0ea4139d37c33cb6eaa16f09404dda345e'
#    entrypoint: 'gcloud'
#    args:
#      - compute
#      - instances
#      - list
#    env:
#      - 'CLOUDSDK_COMPUTE_REGION=us-east1'
#      - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
#
#  - name: 'us-east1-docker.pkg.dev/gcp-asigbahgcp-nprd-47930/cmm/cloud-sdk@sha256:edbae5f175701d837754cbf5402b4c0ea4139d37c33cb6eaa16f09404dda345e'
#    args:
#      - curl --help
#    env:
#      - 'CLOUDSDK_COMPUTE_REGION=us-east1'
#      - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'

logsBucket: 'gs://bah-build-logs/bah-kali-linux-img'

substitutions:
  _USER: "Google Cloud"

options:
  automapSubstitutions: true
  logging: GCS_ONLY
  logStreamingOption: STREAM_ON
#