steps:
  - name: 'us-east1-docker.pkg.dev/gcp-asigbahgcp-nprd-47930/bah-builders/bah-kali-linux-img'
    env:
      - 'KALI_VERSION=2024.2'
      - 'CML_ENDPOINT=https://gcp.becomingahacker.com'
      - 'APT_OPTS="-o Dpkg::Options::=--force-confmiss -o Dpkg::Options::=--force-confnew -o DPkg::Progress-Fancy=0 -o APT::Color=0"'
      - 'DEBIAN_FRONTEND=noninteractive'
      - 'TZ=Etc/UTC'
      - 'PACKER_LOG=1'
      - 'CLOUDSDK_COMPUTE_REGION=us-east1'
      - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
    script: |
      #!/usr/bin/env bash

      set -e
      #set -x

      env

      echo "Locale settings:"
      cat /etc/default/locale

      # SSH key pair for Packer.  Will be removed after build.
      mkdir -vp secrets
      ssh-keygen -t ed25519 -f secrets/id_ed25519 -C "root@kali" -N ""

      # TODO cmm - remove, lighten the load on kali.download
      #curl -s -o kali-linux-${KALI_VERSION}-cloud-genericcloud-amd64.tar.xz https://kali.download/cloud-images/kali-${KALI_VERSION}/kali-linux-${KALI_VERSION}-cloud-genericcloud-amd64.tar.xz
      #tar xJvf kali-linux-${KALI_VERSION}-cloud-genericcloud-amd64.tar.xz
      #gcloud storage cp gs://bah-machine-images/kali-linux/kali-linux-2024.2-cloud-genericcloud-amd64.tar.gz .
      #tar xzvf kali-linux-${KALI_VERSION}-cloud-genericcloud-amd64.tar.gz

      # Build Kali Linux image with Packer
      packer init kali-gce.pkr.hcl
      packer validate -var "service_account_email=$SERVICE_ACCOUNT_EMAIL" kali-gce.pkr.hcl
      packer build -var "service_account_email=$SERVICE_ACCOUNT_EMAIL" kali-gce.pkr.hcl

      # TODO cmm - Try connecting to CML
      #timeout 10s curl -k -v ${CML_ENDPOINT}
      #PASS="$(gcloud secrets versions access 1 --secret admin_password)"
      #echo $PASS 
      #TOKEN="$(curl -s -k -X 'POST' ""${CML_ENDPOINT}/api/v0/authenticate"" -H 'accept: application/json' -H 'Content-Type: application/json' -d '{\"username\": \"admin\", \"password\": \"'$PASS'\"}' | jq -r . )\""
      #curl -k -v -X 'POST' -H \"Authorization: Bearer $TOKEN\" -H 'Content-Type: application/json' --data-binary @/root/node_definition.json '${local.cfg.cml_controller_url}/api/v0/node_definitions'
      #curl -k -v -X 'POST' -H \"Authorization: Bearer $TOKEN\" -H 'Content-Type: application/json' --data-binary @/root/image_definition.json '${local.cfg.cml_controller_url}/api/v0/image_definitions'

logsBucket: 'gs://bah-build-logs/bah-kali-linux-img'
serviceAccount: 'projects/gcp-asigbahgcp-nprd-47930/serviceAccounts/build-bah-kali-linux-img@gcp-asigbahgcp-nprd-47930.iam.gserviceaccount.com'

options:
  logging: GCS_ONLY
  logStreamingOption: STREAM_ON
