steps:
  - name: 'us-east1-docker.pkg.dev/gcp-asigbahgcp-nprd-47930/bah-builders/bah-kali-linux-img'
    script: |
      #!/usr/bin/env bash
      echo "Hello $_USER"
      pwd
      ls -l /dev
      mkdir -vp secrets
      ssh-keygen -t ed25519 -f secrets/id_ed25519 -C "kali@kali"
      bootcmd="echo $(cat secrets/id_ed25519.pub) >> /root/.ssh/authorized_keys"
      sed -i 's/^  boot_command .*$/  boot_command = [ ${bootcmd} ]/' kali.pkr.hcl
      cat kali.pkr.hcl
      packer build kali.pkr.hcl

    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-east1'
      - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'

logsBucket: 'gs://bah-build-logs/bah-kali-linux-img'

substitutions:
  _USER: "Google Cloud"

options:
  automapSubstitutions: true
  logging: GCS_ONLY
  logStreamingOption: STREAM_ON
