steps:
  - name: 'ubuntu'
    args: ['echo', 'hello world'] 
  
  - name: 'ubuntu'
    args:
      - ls
      - -l
      - /workspace
  - name: 'ubuntu'
    script: |
      #!/usr/bin/env bash
      echo "Hello $_USER"
  - name: 'ubuntu'
    script: |
      #!/usr/bin/env bash
      echo "Your project ID is $PROJECT_ID"

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      - compute
      - instances
      - list
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-east1'
      - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'

logsBucket: 'gs://bah-build-logs/bah-kali-linux-img'

substitutions:
  _USER: "Google Cloud"

options:
  automapSubstitutions: true
  logging: GCS_ONLY
  logStreamingOption: STREAM_ON
#