steps:
  - name: 'us-east1-docker.pkg.dev/gcp-asigbahgcp-nprd-47930/bah-builders/bah-kali-linux-img'
    script: |
      #!/usr/bin/env bash

      set -e
      set -x

      echo -n "My IP: "
      curl -s -4 ip.me
      PASS="$(gcloud secrets versions access 1 --secret admin_password)"
      echo $PASS 
      exit 1

      APT_OPTS="-o Dpkg::Options::=--force-confmiss -o Dpkg::Options::=--force-confnew"
      APT_OPTS+=" -o DPkg::Progress-Fancy=0 -o APT::Color=0"
      DEBIAN_FRONTEND=noninteractive
      export APT_OPTS DEBIAN_FRONTEND
      printf "LANG=en_US.UTF-8\nLC_ALL=en_US.UTF-8\n" > /etc/default/locale

      mkdir -vp secrets
      ssh-keygen -t ed25519 -f secrets/id_ed25519 -C "kali@kali" -N ""
      bootcmd="echo $(cat secrets/id_ed25519.pub) >> /root/.ssh/authorized_keys<enter>"

      sed -i 's%  boot_command .*$%  boot_command = \["'"${bootcmd}"'"]%' kali.pkr.hcl

      curl -s -o kali-linux-${KALI_VERSION}-cloud-genericcloud-amd64.tar.xz https://kali.download/cloud-images/kali-${KALI_VERSION}/kali-linux-${KALI_VERSION}-cloud-genericcloud-amd64.tar.xz
      tar xJvf kali-linux-${KALI_VERSION}-cloud-genericcloud-amd64.tar.xz

      # Build Kali Linux image with Packer
      packer init kali.pkr.hcl
      packer build kali.pkr.hcl

      # Copy resultant image to GCS
      gcloud storage cp build/kali-linux.qcow2 gs://bah-machine-images/kali-linux/kali-linux.qcow2

      # Try connecting to CML
      timeout 10s curl -k -v ${CML_ENDPOINT}
      PASS="$(gcloud secrets versions access 1 --secret admin_password)"
      echo $PASS 
      #TOKEN="$(curl -s -k -X 'POST' ""${CML_ENDPOINT}/api/v0/authenticate"" -H 'accept: application/json' -H 'Content-Type: application/json' -d '{\"username\": \"admin\", \"password\": \"'$PASS'\"}' | jq -r . )\""
      #curl -k -v -X 'POST' -H \"Authorization: Bearer $TOKEN\" -H 'Content-Type: application/json' --data-binary @/root/node_definition.json '${local.cfg.cml_controller_url}/api/v0/node_definitions'
      #curl -k -v -X 'POST' -H \"Authorization: Bearer $TOKEN\" -H 'Content-Type: application/json' --data-binary @/root/image_definition.json '${local.cfg.cml_controller_url}/api/v0/image_definitions'


    env:
      - 'KALI_VERSION=2024.2'
      - 'CML_ENDPOINT=https://gcp.becomingahacker.com'
      - 'PACKER_LOG=1'
      - 'CLOUDSDK_COMPUTE_REGION=us-east1'
      - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'

logsBucket: 'gs://bah-build-logs/bah-kali-linux-img'

#substitutions:
#  _USER: "Google Cloud"

options:
  logging: GCS_ONLY
  logStreamingOption: STREAM_ON
