steps:
  - name: 'ubuntu'
    args: ['echo', 'hello world'] 
  
  - name: 'ubuntu'
    args:
      - ls
      - -l
      - /workspace
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - instances
      - list
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-east1'
      - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
