#
# This file is part of Becoming a Hacker Foundations
# Copyright (c) 2024, Cisco Systems, Inc.
# All rights reserved.
#

# TODO cmm - This URL doesn't have a valid certificate.  Would like to use the
# Network Load Balancer URL, but it doesn't work with the current configuration
# from other machines in the VPC.  There is a need to figure out why.  It's
# probably Security Group related.  For now, we'll use the CML Host URL and
# disable certificate checking.  This works inside the VPC, but not the best
# for security.
cml_controller_url: https://cml-0.becomingahacker.com

# AWS configs
aws:
  region: us-east-2
  vpc: cmm-vpc
  availability_zone: us-east-2a
  subnet: cmm-subnet-public1-us-east-2a

  # TODO cmm - CiscoModelingLabs role must not be able to access this bucket
  # Must be globally unique and updated in terraform.tf backend config
  tfstate_bucket: "bah-cml-terraform-state"
  tfstate_key: "bah-kali-linux-img"

  # The EC2 instance type to use when building
  instance_type: c5d.xlarge

  # The security group to use when building
  security_group: default

  # IAM Role for EC2 host to assume
  instance_profile: CiscoModelingLabsBuild

  key_name: bootstrap_ssh
  disk_size: 16

secrets:
  app_password: sto/becomingahacker/secret/common/becomingahacker.com/prod/host/cml-0.becomingahacker.com/admin_password

kali_linux_build_commands:
  - APT_OPTS="-o Dpkg::Options::=--force-confmiss -o Dpkg::Options::=--force-confnew"
  - APT_OPTS+=" -o DPkg::Progress-Fancy=0 -o APT::Color=0"
  - DEBIAN_FRONTEND=noninteractive
  - export APT_OPTS DEBIAN_FRONTEND
  - apt-get update
  - apt-get upgrade -y
  # TODO cmm - What else do we need to install?
  # https://www.kali.org/docs/general-use/metapackages/
  #- apt-get install -y kali-desktop-xfce kali-linux-default docker.io
  - apt-get install -y kali-desktop-xfce docker.io

kali_linux_image_definition:
  id: kali-linux
  node_definition_id: kali-linux
  description: Kali Linux with Xfce Desktop Environment
  label: Kali Linux
  disk_image: kali-linux.qcow2
  read_only: false
  ram:
  cpus:
  cpu_limit:
  disk_subfolder: kali-linux
  schema_version: 0.0.1

kali_linux_node_definition:
  id: kali-linux
  general:
    nature: server
    read_only: false
  device:
    interfaces:
      has_loopback_zero: false
      physical:
        - eth0
        - eth1
        - eth2
      serial_ports: 1
      default_count: 1 
  ui:
    visible: true
    label_prefix: kali-
    icon: host
    label: Kali Linux
    description: |
      Kali Linux with Xfce Desktop Environment

      Git reference: ${module.git_label.git_label}

  sim:
    linux_native:
      libvirt_domain_driver: kvm
      driver: server
      disk_driver: virtio
      ram: 4096
      cpus: 2
      cpu_limit: 100
      boot_disk_size: 32
      nic_driver: virtio
      video:
        model: virtio
        memory: 16
  boot:
    timeout: 10
  inherited:
    image:
      ram: true
      cpus: true
      cpu_limit: true
      data_volume: true
      boot_disk_size: true
    node:
      ram: true
      cpus: true
      cpu_limit: true
      data_volume: true
      boot_disk_size: true
  configuration:
    generator:
      driver: ubuntu
    provisioning:
      volume_name: cidata
      media_type: iso
      files:
        - name: meta-data
          content: |
            instance-id: kali
            local-hostname: kali
          editable: false
        - name: user-data
          content: |
            #cloud-config
            hostname: kali-default
            manage_etc_hosts: True
            system_info:
              default_user:
                name: cisco
            password: cisco
            chpasswd: { expire: False }
            ssh_pwauth: True
            #ssh_authorized_keys:
            #   - your-ssh-pubkey-line-goes-here
          editable: true
  schema_version: 0.0.1
